#!/usr/bin/env jruby

def run(f)
  sh "ruby --1.9 #{f}"
end

task :default => :run

task :run do
  run('example.rb')
end

task :server do
  sh '/Users/frog/.rvm/rubies/jruby-1.6.0/bin/jruby --ng-server'
end

task :run_server do
  sh 'jruby --1.9 --ng -J-server -J-d64 -J-Xmx768m \
      -J-XX:+UseParallelGC lib/metamodel.rb'
end
